# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Weiszfeld_init_rcpp <- function(X, init, weights, epsilon = 1e-08, nitermax = 100L) {
    .Call(`_RobRegression_Weiszfeld_init_rcpp`, X, init, weights, epsilon, nitermax)
}

WeiszfeldCovMat_init_rcpp <- function(X, init_cov, median_est, weights, epsilon = 1e-08, nitermax = 100L) {
    .Call(`_RobRegression_WeiszfeldCovMat_init_rcpp`, X, init_cov, median_est, weights, epsilon, nitermax)
}

Gmedianrowvec_init_rcpp <- function(X, init, weights, gamma = 2, alpha = 0.75, nstart = 1L, epsilon = 1e-8) {
    .Call(`_RobRegression_Gmedianrowvec_init_rcpp`, X, init, weights, gamma, alpha, nstart, epsilon)
}

MedianCovMatRow_init_rcpp <- function(X, init_cov, Gmedian, weights, gamma = 2, alpha = 0.75, nstart = 1L) {
    .Call(`_RobRegression_MedianCovMatRow_init_rcpp`, X, init_cov, Gmedian, weights, gamma, alpha, nstart)
}

